services:
  dev:
    image: mcr.microsoft.com/devcontainers/javascript-node:20-bookworm
    init: true
    command:
      - sleep
      - inf
    volumes:
      - type: volume
        source: tailscale
        target: /var/run/tailscale

  ping:
    image: mcr.microsoft.com/devcontainers/base:bookworm
    init: true
    command:
      - sh
      - -c
      - 'while sleep 5; do date; curl -s checkip.amazonaws.com; done | tee -a /log/log'
    volumes:
      - type: bind
        source: ../log
        target: /log

  tailscale:
    image: tailscale/tailscale:latest
    network_mode: service:ping
    volumes:
      - type: volume
        source: tailscale
        target: /var/run/tailscale
    devices:
      - /dev/net/tun
    init: true
    privileged: true
    command:
      - tailscaled
#     - -tun=userspace-networking
      - '-state=mem:'

volumes:
  log:
  tailscale:
